### ISSUE TITLE
Wireframe Milestone

### ISSUE THREAD

**Issue by shaw0106** [sagehartly/simple-chat-app#8]
# Progress
- [x] Paper Wireframes
  - [x] 404 page
  - [x] Chat (main) page
  - [x] Members List
  - [x] Notifications
    - [x] Joined
    - [x] Left

@ericadamski

**Comment by sagehartly** [comment]
# Issues
Completed all issues regarding creating a cohesive paper wireframes.

# Positives :+1:
+ I thought a lot about UI elements we could bring into the app and brought those in my wireframes. 
+ Finished my wireframe, came to meeting to discuss how to put our wireframes together.

# Improvements :star:
+ Could do more research into other chat apps to see how to improve what I have. 
+ Need to work out a schedule of what's due to better understand what's due.

# Request for Feedback :ear:
+ Unsure of how to make the side menu slide out (code-wise), is this element do-able for us?

**Comment by shaw0106** [comment]
Progress for first sprint: Paper wireframes - complete!

# Positives :+1:

+ Really great at organizing team to accomplish goals, including rescheduling meetings;
+ Good research on possible UI/UX features for chat apps;
+ Great at compromising and completing tasks as needed.

# Improvements :star:

+ Need to improve my personal time management skills;
+ Dates could be more clear on Milestones;
+ More detail for the copy on issues.

# Request for Feedback :ear:

+ Looking for feedback on overall detail on issues. Is it enough?

**Comment by shannonhawn** [comment]
#Issues
+ Completed issues for paper wireframe

# Positives :+1:
+ Researched chat applications
+ Complete tasks on time and collaborated with team

# Improvements :star:
+ Include more details in paper frame wireframe
+ Create more wireframes to hash out different layouts

# Request for Feedback :ear:
+ Looking for feedback on overall design of chat application
